force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Name of Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>Object to save Items related with an Order</description>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000000}</displayFormat>
        <label>Name of Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Field Master-Detail that creates relationship with the Order</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Sum the Quantity per UnitPrice, It&apos;s read only</description>
    <formula>Quantity__c * UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderItemTriggerHandler.cls
public with sharing class OrderItemTriggerHandler extends TriggerHandler {

    public OrderItemTriggerHandler() {
        this.setMaxLoopCount(5);
    }

    public override void afterInsert() {
        List<OrderItem__c> records = Trigger.new;
        validateAllAfters(records, null);
    }

    public override void afterUpdate() {
        List<OrderItem__c> records = Trigger.new;
        Map<Id, OrderItem__c> oldRecords = (Map<Id, OrderItem__c>)Trigger.oldMap;
        validateAllAfters(records, oldRecords);
        
    }

    public override void afterDelete() {
        List<OrderItem__c> records = Trigger.old; // set old values, because new values in after delete not exist
        validateAllAfters(records, null);
        
    }

    private static void validateAllAfters(List<OrderItem__c> records, Map<Id, OrderItem__c> oldRecords) {
        Set<Id> orderIdsTotalAmount = new Set<Id>();
        for(OrderItem__c record : records){
            // validation when TotalPrice__c change or is new or is deleted
            if(record.TotalPrice__c != 0 && (oldRecords == null || record.TotalPrice__c != oldRecords.get(record.Id).TotalPrice__c)){
                orderIdsTotalAmount.add(record.Order__c);
            }
        }

        if(!orderIdsTotalAmount.isEmpty()){
            OrderService.updateOrderTotals(orderIdsTotalAmount);
        }

    }


    

    
}