force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Name of Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <description>Address where the order must be delivered</description>
    <label>Shipping Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <description>This field is autofill by integration with openweathermap</description>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <description>This field is proceeded automatically from trigger, sum the Total Amount from all Item related</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/WeatherDescription__c.field-meta.xml
<CustomField>
    <fullName>WeatherDescription__c</fullName>
    <description>This field is autofill by integration with openweathermap</description>
    <label>WeatherDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/WeatherFillDatetime__c.field-meta.xml
<CustomField>
    <fullName>WeatherFillDatetime__c</fullName>
    <description>Identify the date and time when the weather is calculated using integration</description>
    <label>Weather Fill Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>Object to save Items related with an Order</description>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000000}</displayFormat>
        <label>Name of Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Field Master-Detail that creates relationship with the Order</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Sum the Quantity per UnitPrice, It&apos;s read only</description>
    <formula>Quantity__c * UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderService.cls
public with sharing class OrderService {

    public class OrderServiceException extends Exception {}
    
    public static void updateOrderTotals(Set<Id> orderIds) {
        if (orderIds.isEmpty()) return;

        // Calcular la nueva suma de los OrderItem
        Map<Id, Decimal> orderTotals = new Map<Id, Decimal>();
        for (AggregateResult ar : [
            SELECT Order__c Id, SUM(TotalPrice__c) total 
            FROM OrderItem__c 
            WHERE Order__c IN :orderIds 
            GROUP BY Order__c
        ]) {
            orderTotals.put((Id) ar.get('Id'), (Decimal) ar.get('total'));
        }

        // Actualizar las órdenes con el nuevo total
        List<Order__c> ordersToSave = new List<Order__c>();
        for (Id orderId : orderTotals.keySet()) {
            Decimal total = orderTotals.get(orderId) != null ? orderTotals.get(orderId) : 0;
            Order__c order = new Order__c(Id = orderId);
            order.TotalAmount__c = total;
            ordersToSave.add(order);
        }

        if (!ordersToSave.isEmpty()) {
            if(Schema.Order__c.sObjectType.getDescribe().isUpdateable() && 
            Schema.Order__c.fields.TotalAmount__c.getDescribe().isUpdateable()) {
                update ordersToSave;
            } else {
                throw new OrderServiceException('Invalid Permissions');
            }
        }
    }

    /**
     * Método @future para actualizar el clima en órdenes
     * @param orderIds Ids de las órdenes a actualizar.
     */
    @future(callout=true)
    public static void updateWeatherForOrders(Set<Id> orderIds) {
        if (orderIds.isEmpty()) return;

        List<Order__c> orders = [SELECT Id, ShippingAddress__c FROM Order__c WHERE Id IN :orderIds AND ShippingAddress__c != NULL];
        if (orders.isEmpty()) return;

        List<Order__c> ordersToUpdate = new List<Order__c>();

        for (Order__c order : orders) {
            Map<String, Object> weatherData = WeatherCallout.getWeatherByCity(order.ShippingAddress__c);

            if (weatherData != null && weatherData.containsKey('temperature')) {
                order.Temperature__c = (Decimal) weatherData.get('temperature');
                order.WeatherDescription__c = (String) weatherData.get('description');
                order.WeatherFillDatetime__c = System.now();
                ordersToUpdate.add(order);
            }
        }

        if (!ordersToUpdate.isEmpty()) {
            update ordersToUpdate;
        }
    }
}