force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Name of Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Date on which the order expires</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identify the Status of the order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdersDueIdentifyBatch.cls
public class OrdersDueIdentifyBatch implements Database.Batchable<SObject>, Schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, DueDate__c FROM Order__c WHERE DueDate__c < TODAY]);
    }

    public void execute(Database.BatchableContext BC, List<Order__c> orders) {
        List<Order__c> ordersToUpdate = new List<Order__c>();

        for (Order__c ord : orders) {
            ord.Status__c = 'Overdue';
            ordersToUpdate.add(ord);
        }

        if (!ordersToUpdate.isEmpty()) {
            update ordersToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Batch execution completed');
    }

    // Permite la ejecución programada del batch
    public void execute(SchedulableContext SC) {
        Database.executeBatch(new OrdersDueIdentifyBatch(), 200);
    }
}